title: Chrome Extension Utilities
description: Utility methods for chrome extensions using ES6 modules and typescript
theme: jekyll-theme-cayman
markdown: kramdown
repository: opus1269/chrome-ext-utils
google_analytics: UA-61314754-6
